version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/vrms
    # Add environment variables if needed
    # environment:
    #   - DJANGO_SETTINGS_MODULE=your_project.settings.production
